travis:
  secure:
    BINSTAR_TOKEN: pMOgRpasxB5+et9PHm0KmAp8Rrd+ddZt6EluEnHSLHuGC0jacuCSpFMNDC79W4lLCbWJuEfnAtdPKbcyps6Rb83a6MEcF6t/2jd/rMJZN7hFP5J4jSgUjV115marUetg7BPBcX9hNM7PEAHWJP2U7Tp9rqKQGuYb80ZvyV1Xa889OQyZKitgMtgSqv7fU74/6+fBg1alcjPD9W9f2Rl7bVHVhlRmc3waPXTY1B4N05bryPq3j/FYWzy19mL0P4e+RHV4Eer90RfxAVLfcE7rpD6zwyaxhBSConxjNp7CZpGxt7s4h963fTYQtA5VGUHHXRN4xWjgMUYBF/64OTPcipTPiCtfD9AGANdFFpQG/5fjbFbfWkca2icX1oifo52apJ00Ni5+YK9nI14k3XwxhMsUqLxMc7cwvoYeKYoFJ8dTN8sr/L9hi2YFifjhRsmHCV93K+yX32FybuPX3x4KBN0s4ZslJjXElfjPbsid0D/5hgBUiShi7g+XuHWCGbTbDkGYnSxV6U6TGu8r7oU1reKO1eNJvEa0W7qaC5dXdHE6IO5kgub/flS5ZfdbaaptIPL5DIGjsjYTVnAtW582kZZ1/ErF+2t6mw2lh3BjUNv/fIXIzCcPnxqGy9o3lZA54ikWCx5R/SLwMxFE3JmM8OIzTQX776/oa9+zrW6j7Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
