travis:
  secure:
    BINSTAR_TOKEN: H5dcD9cXdNchBnLoogVnHuoX7JaMboRfx4smgiNNk2m+PrroDOIoEXOPHPt5LyJwaLok2mRM17zVaLExnSGb6jiWXYxu8b5kaeG0yf0QAn18L8jlmv0djLRP9sn+EX2CeQae+bMPxZ4V2E/N3R8SyB3fDjQqSbWmykZIi4CnjHwUhxHAZsCzHXntOPpIV2GS4jH13kLkmx3lFqVGg3+g6d4bgTb5R4MeoBOSK+PEb83Ady+IfzRwK6wp+NuUH1qL7ZWMDbNoIWz2M9TfVXMss4hrFYNGQuDLt+s5swydw/P2VsJN3YbZQxm1ZBHkjB0Shz49qPDMYeki6g1rv8cRj96xHY36HyoCSHKg156x4p9qvdHOcX8tb8KY6Ki/gzplnX+t+j+Gab0QXjKrsxawkBRRJda5ibLycaVfYmiiAuMjIAgNlkEAXpE9m9dDlTAoPO+5nvPTmyklqvMVILLCzRgMK66NzuVs2rk4IZj01TWwVBsOkilupSwQb+xaMSs6Tvyr5c+Fkb6pjnNZmjBqda9pL4aA7pOadSUssiSX6uoH/l0BRLgwvXz5Qt1vrLaBLgCfc6vV2cvSdLwbv9ymjXbIPTnF5c4B8gdnhSMLUySdFWgyE8Hdo6NFA7HHb1gyrEH7LAOKNE1vKytmKYN5gdp80TCti2p58FSaDpi+7Fc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
